alkemyTech/OT229-server

src/main/java/com/alkemy/ong/entities/ActivityEntity.java
src/main/java/com/alkemy/ong/repository/ActivityRepository.java

Se crea entidad y repositorio según OT229-21

Se crea entity y repository de activity

---

src/main/java/com/alkemy/ong/configuration/SendGridConfiguration.java
src/main/java/com/alkemy/ong/services/EmailService.java
src/main/java/com/alkemy/ong/services/ImpEmailService.java

Se implemento un archivo de configuracion de sendgrid
Se implemento el servicio para el envio de emails
Se implemento la interfaz de emails que utiliza el servicio de emails

OT229 27 - Integracion de Envio de Emails

---

src/main/java/com/alkemy/ong/entities/Organization.java
src/main/java/com/alkemy/ong/repositories/OrganizationsRepository.java

Added:
- Entity: Organization
- Repository: OrganizationRepository

finished adding organization's entity and repository

---

src/main/java/com/alkemy/ong/security/configuration/SecurityConfiguration.java
src/main/java/com/alkemy/ong/security/filter/JwtAuthorizationFilter.java

Se añade un filtro en la configuración de Spring Security. Ese filtro verifica el token y autentica la petición con los roles que provee el token JWT

OT229-33 Validar rol

---

src/main/java/com/alkemy/ong/controllers/CategoriesController.java
src/main/java/com/alkemy/ong/dto/CategoryDTO.java
src/main/java/com/alkemy/ong/entities/Category.java
src/main/java/com/alkemy/ong/mappers/CategoryMapper.java
src/main/java/com/alkemy/ong/security/configuration/SecurityConfiguration.java
src/main/java/com/alkemy/ong/services/CategoriesService.java
src/main/java/com/alkemy/ong/services/CategoriesServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

For Categories
Added:
- CategoriesController
- CategoriesRepository
- CategoriesRepositoryImpl
- CategoriesMapper
- CategoriesDTO
Modified:
- SecurityConfiguration
- GlobalConstants

added categories with all necessary layers

---

pom.xml
src/main/java/com/alkemy/ong/dto/UserDTO.java
src/main/java/com/alkemy/ong/mappers/UserMapper.java
src/main/java/com/alkemy/ong/security/payload/LoginResponse.java
src/main/java/com/alkemy/ong/security/service/AuthenticationService.java
src/main/java/com/alkemy/ong/security/service/AuthenticationServiceImpl.java
src/main/java/com/alkemy/ong/security/service/JwtService.java
src/main/java/com/alkemy/ong/security/service/JwtServiceImpl.java
src/main/resources/application.properties

Valores de las propiedades del token sin las variables de entorno
```
token.expires= 86400000
token.secret.key= superSecreto123
token.issuer= ONG - OT229
```

OT229-31-2 Añadir lógica de JWT

---

src/main/java/com/alkemy/ong/OngApplication.java
src/main/java/com/alkemy/ong/security/controller/AuthController.java

Se inyecta el servicio de email para poder enviarle un mail de bienvenida al usuario al momento de registrarse

Envio de email de Bienvenida - OT229-30

---

src/main/java/com/alkemy/ong/controllers/UserController.java
src/main/java/com/alkemy/ong/services/UserService.java
src/main/java/com/alkemy/ong/services/UserServiceImpl.java

Se agregó: 
- método de listar usuarios en el servicio. La lista se encuentra ordenada por email.
- endpoint (con acceso solo para administradores) de listar usuarios.

Ot229 35 Endpoint Listar usuarios

---

src/main/java/com/alkemy/ong/controllers/CategoriesController.java
src/main/java/com/alkemy/ong/controllers/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
src/main/java/com/alkemy/ong/dto/ReducedOrganizationDTO.java
src/main/java/com/alkemy/ong/mappers/OrganizationMapper.java
src/main/java/com/alkemy/ong/repositories/OrganizationsRepository.java
src/main/java/com/alkemy/ong/services/OrganizationService.java
src/main/java/com/alkemy/ong/services/OrganizationServiceImpl.java

**Se realizó:**
- Se creó un endpoint POST, para realizar la actualización de la información de una organización.
- Se cambió el nombre de OrganizationDTO por ReducedOrganizationDTO.
- Se creó la clase OrganizationDTO con más atributos.
- Se creó un método en la clase OrganizationMapper para mapear de la entidad Organization a OrganizationDTO.
- Se agregó el método para actualizar la información de una organización en la interfaz OrganizationService.
- Se implementó el método para actualizar la información de una organización.

OT229-37 Endpoint para actualización de datos públicos de Organización

---

src/main/java/com/alkemy/ong/controllers/UserController.java
src/main/java/com/alkemy/ong/dto/UserDTO.java
src/main/java/com/alkemy/ong/dto/UserDTORequest.java
src/main/java/com/alkemy/ong/mappers/UserMapper.java
src/main/java/com/alkemy/ong/services/UserService.java
src/main/java/com/alkemy/ong/services/UserServiceImpl.java

-Creación de endpoint para actualizar usuario, recibe un usuario y una imagen
-Creación e implementación del método para actualizar el usuario en el servicio, si el usuario se ecuentra borrado no se puede actualizar y si los campos vienen vacíos el usuario permanece con sus valores anteriores.

Ot229 34 Endpoint de actualizar usuario

---

src/main/java/com/alkemy/ong/controllers/CloudStorageController.java
src/main/java/com/alkemy/ong/services/impl/AmazonS3ServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/CategoriesServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/EmailServiceImp.java
src/main/java/com/alkemy/ong/services/impl/OrganizationServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java

-added package "Impl" in services

changes in package

---

src/main/java/com/alkemy/ong/repositories/RoleRepository.java
src/main/java/com/alkemy/ong/security/controller/AuthController.java
src/main/java/com/alkemy/ong/security/payload/SignupRequest.java
src/main/java/com/alkemy/ong/security/payload/SingupResponse.java
src/main/java/com/alkemy/ong/security/service/impl/AuthenticationServiceImpl.java
src/main/java/com/alkemy/ong/security/service/impl/JwtServiceImpl.java
src/main/java/com/alkemy/ong/security/service/impl/UserDetailsServiceImpl.java
src/main/java/com/alkemy/ong/services/RoleService.java
src/main/java/com/alkemy/ong/services/UserService.java
src/main/java/com/alkemy/ong/services/impl/RoleServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java

Descripción:
- Se cambio la logica de crear usuario. Se paso del controlador al servicio correspondiente.
- Se le asigna el rol de usuario a un nuevo registro.
- Se guarda el usuario con la foto (si es que esta).
- El endpoint devuelve un response de la información del usuario creado y el token jwt.
Imagen del response:
https://files.slack.com/files-pri/T017S5VTHU1-F03MKJBD03D/sin_t__tulo.png

OT229-49 Devolver token al usuario luego de registrarse en el sitio

---

src/main/java/com/alkemy/ong/controllers/UserController.java
src/main/java/com/alkemy/ong/services/UserService.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java

se modifico el servicio de usuario para que valida que el email no este repetido.
se cambiaron los return del endpoint para que devuelva el mensaje de cada excepcion.
se cambio el http status del endpoint de delete para que devuelva un 204.

Changes user controller and service

---

src/main/java/com/alkemy/ong/dto/ContactDTORequest.java
src/main/java/com/alkemy/ong/dto/ContactDTOResponse.java
src/main/java/com/alkemy/ong/entities/Contact.java
src/main/java/com/alkemy/ong/mappers/ContactMapper.java
src/main/java/com/alkemy/ong/repositories/ContactRepository.java
src/main/java/com/alkemy/ong/services/ContactService.java
src/main/java/com/alkemy/ong/services/impl/ContactServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/ContractServiceImpl.java

-Se crea Entidad Contacto
-Se crea Repositorio y servicio correspondiente
-Se crea mapper
-Se crean los DTO para Request y Response

Ot229 53 Crear modelo, repositorio y servicio de contacto.

---

src/main/java/com/alkemy/ong/controllers/OrganizationController.java
src/main/java/com/alkemy/ong/dto/OrganizationInfoResponse.java
src/main/java/com/alkemy/ong/dto/SlidesEntityDTO.java
src/main/java/com/alkemy/ong/entities/SlidesEntity.java
src/main/java/com/alkemy/ong/mappers/SlidesEntityMapper.java
src/main/java/com/alkemy/ong/repositories/SlideRepository.java
src/main/java/com/alkemy/ong/services/OrganizationService.java
src/main/java/com/alkemy/ong/services/SlidesService.java
src/main/java/com/alkemy/ong/services/impl/OrganizationServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/SlidesServiceImpl.java

Este ticket pedía expandir el ticket anterior OT229-23 de @exerazor1911 :
> **OT229-23**
> COMO usuario
> QUIERO ver los datos de una Organización
> PARA tener conocimiento sobre ella.
> 
> Criterios de aceptación: 
> 
>     Se debe realizar una petición GET hacia ruta /organization/public
> 
>     El endpoint debe devolver solamente los campos name, image, phone y address de la Organización
con la adición de que además de devolver la información de la organización, también retorne las Slides asociadas a dicha org.
Como todavía no había nada de slides creado excepto la entidad y el repo, se crearon las clases necesarias.

Agregar Slides a endpoint público (OT229-60)

---

src/main/java/com/alkemy/ong/controllers/ContactController.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

-Se creó endpoint para almacenar un contacto cuando llena un formulario.
-Se agregó la ruta del controlador en las constantes globales.

OT229-54 Endpoint de almacenar contactos

---

src/main/java/com/alkemy/ong/controllers/SlidesController.java
src/main/java/com/alkemy/ong/services/SlidesService.java
src/main/java/com/alkemy/ong/services/impl/SlidesServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

- Se creó el controlador con el endpoint GET correspondiente.
- Se agregó en la interfaz "SlidesService" el método "findById".
- Se creó la lógica para el método "findById".
- Se agregó la constante del controlador en la clase de constantes globales.
En caso de no encontrar una slide con el ID que se provee, se devuelve el código 404. En caso contrario se devuelve el código 200

OT229-56 Endpoint Detalle Slides

---

src/main/java/com/alkemy/ong/controllers/ContactController.java
src/main/java/com/alkemy/ong/controllers/UserController.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java

@Valid en endpoint de actualizar usuario y crear contacto.
Se quita el reversed de la lista de usuario para que se ordenen de forma ascendente

Pequeños cambios en endpoints de usuario y contacto

---

src/main/java/com/alkemy/ong/controllers/SlidesController.java
src/main/java/com/alkemy/ong/dto/ReducedSlideDTO.java
src/main/java/com/alkemy/ong/mappers/SlidesEntityMapper.java
src/main/java/com/alkemy/ong/repositories/SlideRepository.java
src/main/java/com/alkemy/ong/services/SlidesService.java
src/main/java/com/alkemy/ong/services/impl/SlidesServiceImpl.java

- Se agregó el endpoint para obtener un listado de slides.
- Se creó la clase "ReducedSlideDTO" para mostrar la información correspondiente en el response.
- Se agregó un método en la clase "SlidesEntityMapper" para mapear un ReducedDTO desde la entidad Slides.
- Se agregó el método "slideList" para obtener el listado de Slides en la interfaz "SlidesService"
- Se creó la lógica en el método "slideList" para devolver una lista ordenada de slides.

OT229-55 Endpoint Listado de Slides #2

---

src/main/java/com/alkemy/ong/services/EmailService.java
src/main/java/com/alkemy/ong/services/impl/ContactServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/EmailServiceImp.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java
src/main/resources/templates/plantilla_email.html

-Se agregaron constantes globales para la bienvenida y el formulario de contacto, asi como tambien para los titulos de las plantilla del email.
-se modificó el servicio del email para que envíe un email de acuerdo a si es registro o formulario de contacto

Ot229 62 Enviar email de contacto

---

src/main/java/com/alkemy/ong/dto/ReducedOrganizationDTO.java
src/main/java/com/alkemy/ong/mappers/OrganizationMapper.java

Se agregaron los atributos de las redes sociales en la clase ReducedOrganization la cual devuelve los datos publico de organization.

Modificar endpoint público de organizations para devolver links de redes sociales. OT229-64

---

src/main/java/com/alkemy/ong/controllers/SlidesController.java
src/main/java/com/alkemy/ong/mappers/SlidesEntityMapper.java
src/main/java/com/alkemy/ong/services/SlidesService.java
src/main/java/com/alkemy/ong/services/impl/SlidesServiceImpl.java

Se agrega update

---

src/main/java/com/alkemy/ong/controllers/TestimonialController.java
src/main/java/com/alkemy/ong/dto/TestimonialDTORequest.java
src/main/java/com/alkemy/ong/dto/TestimonialDTOResponse.java
src/main/java/com/alkemy/ong/mappers/TestimonialMapper.java
src/main/java/com/alkemy/ong/services/TestimonialService.java
src/main/java/com/alkemy/ong/services/impl/TestimonialServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

Added:
-Testimonial controller with it endpoint to create testimonials
-Testimonial service (interface and implementation)
-Global constants -> TESTIMONIALS="/testimonials"
-Testimonial mapper
-Testimonial DTOs Request and Response

Ot229 65 ENDPOINT CREACION TESTIMONIOS

---

src/main/java/com/alkemy/ong/controllers/MemberController.java
src/main/java/com/alkemy/ong/dto/MemberDTORequest.java
src/main/java/com/alkemy/ong/dto/MemberDTOResponse.java
src/main/java/com/alkemy/ong/mappers/MemberMapper.java
src/main/java/com/alkemy/ong/services/MemberService.java
src/main/java/com/alkemy/ong/services/impl/MemberServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

Se agrego dtoRequest,dtoResponse y DTO de Member.
Se agrego el controlador de Member con endpoint para almacenar members.
Se agrego servicio de Member incluido el metodo para almacenar members, se verifica con un regx que el campo name tenga un formato valido.

Endpoint Creacion Miembros. OT229-69

---

src/main/java/com/alkemy/ong/controllers/TestimonialController.java
src/main/java/com/alkemy/ong/services/TestimonialService.java
src/main/java/com/alkemy/ong/services/impl/TestimonialServiceImpl.java

Added:
-Method to update testiominals in Testimonials Service.
-Endpoint to update testimonials in Testimonials Controller.

Ot229 66 Actualizacion de testimonios

---

src/main/java/com/alkemy/ong/controllers/TestimonialController.java
src/main/java/com/alkemy/ong/entities/Testimonial.java
src/main/java/com/alkemy/ong/services/TestimonialService.java
src/main/java/com/alkemy/ong/services/impl/TestimonialServiceImpl.java

Added:
-Method to delete testimonials in Testimonial Service Impl
-Endpoint to delete testimonials in Testimonial Controller
-@SQLdelete in Testimonial Entity

Ot229 67 Enpoint eliminacion de testimonios

---

src/main/java/com/alkemy/ong/dto/CommentDTO.java
src/main/java/com/alkemy/ong/entities/CommentEntity.java
src/main/java/com/alkemy/ong/repositories/CommentRepository.java
src/main/java/com/alkemy/ong/services/CommentService.java

modelo, repositorio y servicio de Comentarios

modelo, repositorio y servicio de Comentarios ot229-74

---

src/main/java/com/alkemy/ong/controllers/MemberController.java
src/main/java/com/alkemy/ong/dto/MemberDTORequest.java
src/main/java/com/alkemy/ong/mappers/MemberMapper.java
src/main/java/com/alkemy/ong/services/MemberService.java
src/main/java/com/alkemy/ong/services/impl/MemberServiceImpl.java

Se agrego endpoint para listar miembros
Se agrego el metodo requerido para listar miembros en el servicio
Por ultimo se hicieron unas pequeñas modificaciones en el dto request de member (se eliminaron unas lineas que ya no iban) y tambien se hicieron unas pequeñas modificaciones en el metodo para almacenar miembros.

Endpoint para listar Miembros. OT229-68

---

src/main/java/com/alkemy/ong/controllers/MemberController.java
src/main/java/com/alkemy/ong/repositories/MembersRepository.java
src/main/java/com/alkemy/ong/services/MemberService.java
src/main/java/com/alkemy/ong/services/impl/MemberServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

Se agrega paginación al endpoint de listar miembros.
Como el endpoint original sin paginación es necesario para la demo, se dejó comentado, luego de cambia en un futuro PR.

Agregar paginación a Miembros (OT229-82)

---

src/main/java/com/alkemy/ong/controllers/CommentController.java
src/main/java/com/alkemy/ong/dto/CommentDTOList.java
src/main/java/com/alkemy/ong/mappers/CommentMapper.java
src/main/java/com/alkemy/ong/repositories/CommentRepository.java
src/main/java/com/alkemy/ong/services/CommentService.java
src/main/java/com/alkemy/ong/services/impl/CommentServiceImpl.java

creacion de metodo para listar comentarios ordenados por fecha de creacion, creacion de endpoint para listar dichos comentarios, creacion de query en el repositorio, se agrego metodo en el mapper para mapear la entidad comentario a comentarioDTOList

OT229-75: Endpoint para listar comentarios

---

src/main/java/com/alkemy/ong/controllers/TestimonialController.java
src/main/java/com/alkemy/ong/services/TestimonialService.java
src/main/java/com/alkemy/ong/services/impl/TestimonialServiceImpl.java
src/main/java/com/alkemy/ong/utility/GlobalConstants.java

Added: 
- Pagination to testimonial
- Key to GlobalConstants regarding testimonial pagination
- Endpoint granted for testimonial users GET in globalconstants
Modified:
- TestimonialController
- TestimonialService
- TestimonialServiceImpl

ot229-83 finished

---

src/main/java/com/alkemy/ong/controllers/CategoriesController.java
src/main/java/com/alkemy/ong/controllers/MemberController.java

Se documentaron todos los endpoints correspondientes a categoria.
Se modifico la ruta en el metodo delete de categoria porque daba un error 405 al ejecutarlo en postman, estaba mal escrita la ruta.

Agregar documentación a categorías. OT229-85

---

src/main/java/com/alkemy/ong/dto/OrganizationDTO.java
src/main/java/com/alkemy/ong/dto/OrganizationDTORequest.java
src/main/java/com/alkemy/ong/services/impl/OrganizationServiceImpl.java
src/test/java/com/alkemy/ong/controllers/OrganizationControllerTest.java

Test endpoints Organization (OT229-92)

---

src/main/java/com/alkemy/ong/dto/EncodedImageDTO.java
src/main/java/com/alkemy/ong/dto/UserDTO.java
src/main/java/com/alkemy/ong/security/configuration/ValidationControllerAdvice.java
src/main/java/com/alkemy/ong/security/controller/AuthController.java
src/main/java/com/alkemy/ong/security/payload/LoginRequest.java
src/main/java/com/alkemy/ong/security/payload/LoginResponse.java
src/main/java/com/alkemy/ong/security/payload/SignupRequest.java
src/main/java/com/alkemy/ong/security/payload/SimpleStatusResponse.java
src/main/java/com/alkemy/ong/security/payload/SingupResponse.java
src/main/java/com/alkemy/ong/services/UserService.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java
src/main/java/com/alkemy/ong/utility/FileManager.java

Detecté dos problemitas al escribir la documentación:
1) Se estaban manejando mal unas excepciones en register, arreglé eso.
2) El cuerpo de una respuesta de error en el login era un HashMap. Para poder documentarlo lo reemplacé por un nuevo DTO de respuesta.

Documentación con Swagger para los endpoints de autenticación (OT229-89)

---

src/main/java/com/alkemy/ong/controllers/ContactController.java
src/test/java/com/alkemy/ong/controllers/ContactControllerTests.java

Tests del controlador de contacto
100% de cobertura

OT229-95 Test de endpoint de contacto

---

src/main/java/com/alkemy/ong/dto/ActivityDTORequest.java
src/main/java/com/alkemy/ong/services/ActivitiesService.java
src/main/java/com/alkemy/ong/services/impl/ActivitiesServiceImpl.java
src/test/java/com/alkemy/ong/controllers/ActivitiesControllerTest.java

**Tests:**
- Valid case (POST and PUT)
- Invalid role (POST and PUT)
- Name already exist (POST and PUT)
- Token not valid (POST and PUT)
- Token not provided (POST and PUT)
- Missing atributtes (POST and PUT)
- Blank atributtes (POST and PUT)
- Non-existing ID (PUT)

OT229-94 Test: Endpoints /activities

---

src/main/java/com/alkemy/ong/controllers/NewsController.java
src/main/java/com/alkemy/ong/dto/NewsDTO.java
src/main/java/com/alkemy/ong/dto/NewsDTORequest.java

Documentación agregada a los endpoints y DTO.
Por favor revisar y comentar si hay algún faltante ! 😄

OT229-86 Agregar documentación a Novedades

---

src/main/java/com/alkemy/ong/dto/UserDTORequest.java
src/test/java/com/alkemy/ong/controllers/UserControllerTest.java

**All test done - 100% coverage**

OT229-90 Test: Endpoints /users

---

src/test/java/com/alkemy/ong/controllers/TestimonialControllerTest.java

OT229-98: Testimonial Controller Test. 100%coverage

---

src/test/java/com/alkemy/ong/controllers/NewsControllerTest.java

Endpoints tested:
Save News 100%
Delete News 100%
Get News 100%
Get all news 100%
Update news 100%

News controller test added. OT229-93

---

src/main/java/com/alkemy/ong/entities/Contact.java
src/main/java/com/alkemy/ong/services/impl/ContactServiceImpl.java
src/main/java/com/alkemy/ong/services/impl/TestimonialServiceImpl.java
src/test/java/com/alkemy/ong/services/impl/ContactServiceImplTest.java

Test contact service

---

src/main/java/com/alkemy/ong/entities/ActivityEntity.java
src/main/java/com/alkemy/ong/services/impl/ActivitiesServiceImpl.java
src/test/java/com/alkemy/ong/services/impl/ActivitiesServiceImplTest.java

OT229-94 Test ActivitiesService

---

src/main/java/com/alkemy/ong/exception/RegisterException.java
src/main/java/com/alkemy/ong/services/impl/UserServiceImpl.java
src/test/java/com/alkemy/ong/services/impl/UserServiceImplTest.java

OT229-90 Test UserServiceImpl

---

README.md

Se crea la tabla con los datos de los usuarios de prueba en el readme, requerimiento que quedaba pendiente del ticket 72

Readme created and info added
